apiVersion: v1
kind: Service
metadata:
  name: documentation-app
  namespace: documentation-app
  labels:
    run: documentation-app
spec:
  ports:
  - port: 5005
    protocol: TCP
  selector:
    run: documentation-app